# Generated by Django 3.1.7 on 2021-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition_Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolID', models.CharField(max_length=50)),
                ('academic_level', models.CharField(max_length=200)),
                ('academic_year', models.IntegerField()),
                ('tuition', models.IntegerField()),
                ('clothing', models.IntegerField()),
                ('furniture', models.IntegerField()),
                ('books', models.IntegerField()),
                ('misc', models.IntegerField()),
            ],
        ),
    ]
